// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8hdBHvr7mvjTO4rS0APTMEwJnX9-3zyQ',
    appId: '1:394017406714:web:44a30f6fec45b34389d343',
    messagingSenderId: '394017406714',
    projectId: 'payflow-rocktseat-28724',
    authDomain: 'payflow-rocktseat-28724.firebaseapp.com',
    storageBucket: 'payflow-rocktseat-28724.appspot.com',
    measurementId: 'G-0FCVCXRHP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtGYqn0cFjtx4o4J4RPGckpOmUXCdfzUo',
    appId: '1:394017406714:android:3b889672937d145089d343',
    messagingSenderId: '394017406714',
    projectId: 'payflow-rocktseat-28724',
    storageBucket: 'payflow-rocktseat-28724.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjkjYg6Gt4Fims6ikqklg5piRBN_27sZY',
    appId: '1:394017406714:ios:5048b48e69ae54d089d343',
    messagingSenderId: '394017406714',
    projectId: 'payflow-rocktseat-28724',
    storageBucket: 'payflow-rocktseat-28724.appspot.com',
    iosClientId: '394017406714-u2cmslqc0n0uqlos81j72tn0tu6ppfj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.playflowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjkjYg6Gt4Fims6ikqklg5piRBN_27sZY',
    appId: '1:394017406714:ios:5048b48e69ae54d089d343',
    messagingSenderId: '394017406714',
    projectId: 'payflow-rocktseat-28724',
    storageBucket: 'payflow-rocktseat-28724.appspot.com',
    iosClientId: '394017406714-u2cmslqc0n0uqlos81j72tn0tu6ppfj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.playflowApp',
  );
}
